### ISSUE TITLE
Support Archived CRAN packages

### ISSUE THREAD

**Issue by trestletech** [rstudio/packrat#196]
`quantmod` used to (transitively?) depend on the `Defaults` package. So having Packrat pickup a dependency on an old `quantmod` package will fail to be restored by Packrat since the CRAN page for Defaults is now this: http://cran.r-project.org/web/packages/Defaults/.

When you upgrade to a later version of `quantmod` that doesn't have that dependency, things work fine. It seems undesirable that a package being deprecated by CRAN could revoke our ability to be reproducible.

**Comment by kevinushey** [comment]
Maybe I'm misunderstanding a bit here, but packrat definitely does know how to retrieve source packages from the CRAN archives.

When attempting to retrieve a CRAN package, packrat will:

1. Check to see if the package is 'current'; if so, it'll get it directly from CRAN (and maybe get a binary if available),
2. Otherwise, fall back and check the archives, and install from source from there.

Can you elaborate / illustrate the problem a bit more, perhaps with a reproducible example?

**Comment by trestletech** [comment]
Oh, ok. We were sort of filling in the gaps here around a bug we saw, so I don't have hard proof that this is a bug. I'll close it until if/when I have a smoking gun.
