### ISSUE TITLE
Why doesn't packrat support running in packages?

### ISSUE THREAD

**Issue by dlebauer** [rstudio/packrat#31]
I have gotten in the habit of using the R packaging system to organize projects. I put scripts in a folder such as `vignettes`, `scripts`, or `inst/manuscript`. I wanted to test out using packrat and encountered the "Packrat doesn't work when the packages." message from the `bootstrap` function. Is this to be read "Packrat is not intended to work on packages" or "Packrat does not currently support packages"? I read the documentation and did not find any mention of support for use with packages, and can not understand why this would be disabled by default.

If there is a reason for not using it in the package root directory, would you recommend that I bootstrap directories within the package (like the vignettes folder)?

**Comment by denisesenguel** [comment]
Any progress on this issue?

**Comment by kevinushey** [comment]
There has been substantial progress on using packrat within the context of R package development, but there may yet be some edge cases to resolve (especially in the context of using packrat + R package + RStudio all together). Feel free to give it a whirl and raise an issue if you have trouble!

**Comment by bperaHSA** [comment]
I'm having trouble with **devtools::load_all().  Namely, that it is not attaching the imports in my namespace file.**  My suspicion is that it is related to packrat.  I had also cleaned up the /R directory with formatR shortly before the problem appeared.  

For now I'm stuck using Depends instead of Imports in my DESCRIPTION file and/or using package:: prefixes only.  Not a terrible workaround but not a best practice either which is rather irritating. I wonder if anyone else has come across the issue or if anyone has hints for me to try.  

(I already reset my project back via git to the last commit before the formatR tidy_dir and the problem still persists.)

**Comment by IsaacVerm** [comment]
What's the current status of packrat within packages?

**Comment by anhqle** [comment]
I'm using `packrat` fine during package development. I just had to set `infer.dependencies = FALSE` in `packrat::init()` and manually install the dependencies with the correct versions. It seems that `packrat` does not infer dependencies from the `DESCRIPTION` file yet, and instead search for `library()` and `required()` in R scripts.

**Comment by dlebauer** [comment]
Closing b/c packrat is superseded by renv, and question is >10yo
