### ISSUE TITLE
with_extlib without the package?

### ISSUE THREAD

**Issue by r2evans** [rstudio/packrat#488]
The function name `with_extlib` suggests to me that I can execute an expression with the `extlib` library-path available to the expression. I understand that the function purpose is really "run something with an external-library *package* loaded temporarily", in which case I interpret it to really *mean* `with_extlib_package`. I'm not suggesting changing the name (likely too hard), but I would hope to be able to do something like:

```r
packrat::with_extlib(expr=packageVersion("testthat"))
```

This fails for two reasons, obviously. If I instead do

```r
packrat::with_extlib(character(0), packageVersion("testthat"))
```

I can bypass the first safeguard (`(is.character(packages)`), but unfortunately the presence of the external library is only given to the `library` call, not the expression itself.

This is a specific use-case, granted, though I can envision a more-extensive expression that relies on a package and perhaps implied dependencies. For instance, perhaps I need to access a specific function within the package but do not want to full attach it, e.g., `package::variable`, which results in the namespace being loaded but not attached to the search path.

The following code works (when I strong-arm things in `browser`).

```diff
     local({
         tryCatch({
             oldSearch <- search()
             libPaths <- .packrat_mutables$get("origLibPaths")
+            oldLibPaths <- .libPaths()
             if (!length(libPaths)) 
                 libPaths <- getDefaultLibPaths()
+            .libPaths(libPaths)
             for (package in packages) {
                 library(package, character.only = TRUE, lib.loc = libPaths, 
                   warn.conflicts = FALSE)
             }
             error <- try(res <- eval(call$expr, envir = envir), 
                 silent = TRUE)
             if (exists("res", envir = environment(), inherits = FALSE)) {
                 res
             }
             else {
                 stop(attr(error, "condition")$message, call. = FALSE)
             }
         }, finally = {
             newSearch <- search()
             for (path in setdiff(newSearch, oldSearch)) {
                 try(forceUnload(path))
             }
+            .libPaths(oldLibPaths)
         })
     })
```

The use of `lib.loc = libPaths` is not strictly required. It could be extended to be `.libPaths(c(libPaths, oldLibPaths))` if you feel the need, I don't have a strong feeling at this point.

I can submit a PR if this discussion is fruitful, what do you think of this type of change?

**Comment by r2evans** [comment]
Perhaps a better use-case: within this project directory, I have neither `devtools` nor `roxygen2`. If I want to load it (or another) into this instance of R, I would like to be able to do something like this:

```r
packrat::off()
# Packrat mode off. Resetting library paths to:
# - "C:/Users/me/R/win-library/3.5"
# - "c:/R/R-3.5.1/library"
packageVersion("dplyr")
# [1] '0.7.6'
packageVersion("devtools")
# [1] '1.13.6'
packageVersion("roxygen2")
# [1] '6.1.0'
packrat::on()
# Packrat mode on. Using library in directory:
# - "c:/Users/me/myproj/packrat/lib"
packrat::with_extlib("devtools", devtools::load_all("~/myproj"))
# 'roxygen2' >= 5.0.0 must be installed for this functionality.
# Would you like to install it?
# 1: Yes
# 2: No
```

(Neither `"devtools"` nor `"roxygen2"` are or should need to be installed in the project directory.)

**Comment by cderv** [comment]
One idea could be for packrat to use `withr` function. Something like `withr::with_libpaths(getDefaultLibPaths(), {expr}, action = "suffix")` ?

**Comment by r2evans** [comment]
That's exactly the behavior I was suggesting, thank you @cderv. In my project it works (since something else depends on `withr`), but this won't work if `withr` is not within the local packrat lib-path. I think my suggested diff above (and perhaps not complaining if `packages` is not provided) would provide this capability.

**Comment by kevinushey** [comment]
For what it's worth, I think `with_extlib()` was somewhat misguided as unfortunately attempts to load and unload an R package within the same session often don't go as well as hoped (especially when that package uses compiled code).

If you really want to use an external library in your Packrat project, I think it should just be appended to the library paths.

That said, this reminds me of this post on R-devel: http://r.789695.n4.nabble.com/Library-lib-loc-Option-Ignored-for-Dependencies-td4751097.html

For that reason it's probably better to just set the library paths (as you suggest) rather than setting `lib.loc`. Resetting of the library paths would need to happen in an `on.exit()` handler to accommodate errors that occur and aren't caught though.

**Comment by r2evans** [comment]
I understand your first paragraph. I'm not certain I see if or how my change would break things based on the nabble link you provided.

It sounds like you're amenable to a PR based on my diff above, is that correct?

> Resetting of the library paths would need to happen in an `on.exit()` handler 

Isn't that what the `finally=` step is doing?

**Comment by kevinushey** [comment]
My point was that your change would fix potential issues: if I understand correctly, when dependent packages are loaded, R will search `.libPaths()` rather than `lib.loc` -- so if your package + its dependencies all live in an external library path, but you attempt to load with `lib.loc`, R might fail to discover the dependent packages.

Sorry, you're right as well about the cleanup in `finally = <...>` -- I was skimming and missed that fact. (doh)
