### ISSUE TITLE
SAT solver resolution for dependency management

### ISSUE THREAD

**Issue by stefanoborini** [rstudio/packrat#585]
What is the algorithm packrat uses to resolve the dependency network? Is there a SAT solver implementation for packrat to ensure constraints have been solved appropriately or is it a naive approach?

**Comment by kevinushey** [comment]
Packrat doesn't include a dependency solver, because it doesn't solve dependencies -- it simply records the library state at some point in time, and assumes that the library state is already consistent. Hence, all it needs to do is record packages, their versions, and their sources and know how to retrieve and install packages from those sources.

In other words, the "dependency solver" problem is pushed upstream, to the package used by the user to install packages in the first place. That said, in general packages in the R ecosystem generally attempt to work with the latest versions of their dependencies; it's less common to see version pinning.

There are other packages (e.g. [pak](https://pak.r-lib.org/)) that do implement proper dependency resolvers.

**Comment by stefanoborini** [comment]
Thank you for your reply!
